### ISSUE TITLE
Requesting licensing information

### ISSUE THREAD

**Issue by bodangren** [eannefawcett/lexile-determination-v2#4]
Hello,

I'm also a teacher and beginning to work on a text-complexity scale designed for English-as-a-second-language learners in my school and hopefully others. Your project is impressive looks like it could be one piece to what I want, in addition to CEFR levels and some other text-complexity measures. I don't see a license file on your project. Is your code under a copyleft or MIT-style license?

**Comment by PizBernina** [comment]
Would also be interested :)

**Comment by eannefawcett** [comment]
It's under an MIT license. Thanks for opening an issue! Additionally, I'll be retraining the model used for this project to hopefully git higher specificity for grade levels soon.
