### ISSUE TITLE
v3 - updated version and llm comparison

### ISSUE THREAD

**Issue by PizBernina** [eannefawcett/lexile-determination-v2#5]
Hi, amazing work!
I would like to play around a bit with the structure and add more data. Happy to share it with you once done.

Further, have you tried out some LLMs for the same use case? If so, what is your experience with it?

**Comment by eannefawcett** [comment]
Thanks for your question. This application is built using an LLM. I ended up using a two layer neural network and it is stored separately from this application deployment. I am planning to retrain and update this application in 2025 and privately host it on a local server. I was disappointed that the developed model wasn't able to give more fine grained specificity for predictions. I am hoping that over time, as I add more data, whilst maintaining the ability to keep this project fully open source and completely free, that predictions will become more fine grained.
